name: Docker Build/Publish CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: deployer

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get changed files
        id: getfile
        run: echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD)"

      - name: Build / Push
        run: bash build.sh "${REPOSITORIES}" "${{ steps.getfile.outputs.files }}"